### ISSUE TITLE
Add RSS serializers for RSS versions 0.91, 1.0

### ISSUE THREAD

**Issue by mhl10** [arXiv/arxiv-feed#16]
RSS 2.0 should be the default, but it would be nice to support 0.91 and 1.0 for backwards compatibility.

**Comment by alefnula** [comment]
Support for version header added. But only new version supported.

**Comment by alefnula** [comment]
Supporting old versions would require hand crafting a serializer since none of the libraries support those versions and I don't think anyone depends on them so I'll close this issue. Martin you can reopen it if you don't agree.

**Comment by mhl10** [comment]
@alefnula I agree, thanks for looking into it.
