### ISSUE TITLE
Add PDF URLs as media element

### ISSUE THREAD

**Issue by mhl10** [arXiv/arxiv-feed#17]
> Dear arXiv,
>   My name is David, and I work in the Feedly platform team.
>   Let me start by thanking you for the vital service you provide to the scientific community with your RSS feeds: this is an invaluable tool, and thousands of Feedly readers rely on your feeds for their work.
>   One request we often get from Feedly readers is a faster way to access the PDF documents. There is no link to the PDF in the RSS feed, so readers have to click on the article link in Feedly to open arXiv.org page, then click on the PDF link in that page to open it. Being able to open the PDF directly from Feedly would save time and resources.
>   Feedly can extract PDF URLs and display them in the article. Would it be possible for you to add that URL as a media element in your RSS feeds, using the (commonly used) media RSS extension?
>   Here's an example of what it would look like:
> 
> <media:group>
>     <media:title>Optimizing Energetic Light Dark Matter Searches in Dark Matter and Neutrino Experiments</media:title>
>     <media:content url="https://arxiv.org/pdf/2003.07369.pdf" type="application/pdf"/>
> </media:group>
> 
>   (namespace: xmlns:media="http://search.yahoo.com/mrss/").
>   Is that something you would consider?
>   Best regards,
> 
> -- 
> David
> Feedly

I think this a great suggestion.

**Comment by alefnula** [comment]
Implemented in https://github.com/arXiv/arxiv-feed/pull/19
